In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\91935\DA Projects\capstone_village_api\data_cleaning\cleaned\subdistricts.csv")
df.head(10)

   subdistrict_code subdistrict_name  district_code
0              83.0            Pangi             23
1              84.0          Chaurah             23
2              85.0           Saluni             23
3              86.0           Bhalai             23
4              87.0        Dalhousie             23
5              88.0        Bhattiyat             23
6              89.0          Sihunta             23
7              90.0           Chamba             23
8              91.0             Holi             23
9              92.0         Brahmaur             23

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   subdistrict_code  5042 non-null   float64
 1   subdistrict_name  5042 non-null   object
 2   district_code     5043 non-null   int64
dtypes: float64(1), int64(1), object(1)
memory usage: 118.3+ KB

In [8]:
df.duplicated().sum()

np.int64(0)

In [11]:
df2 = pd.read_csv(r"C:\Users\91935\DA Projects\capstone_village_api\data_cleaning\cleaned\districts.csv")

In [12]:
df2.head(15)

    district_code  district_name  state_code
0              23         Chamba           2
1              24         Kangra           2
2              25  Lahul & Spiti           2
3              26          Kullu           2
4              27          Mandi           2
5              28       Hamirpur           2
6              29            Una           2
7              30       Bilaspur           2
8              31          Solan           2
9              32        Sirmaur           2
10             33         Shimla           2
11             34        Kinnaur           2
12             35      Gurdaspur           3
13             36     Kapurthala           3
14             37      Jalandhar           3

In [13]:
df.head(10)

   subdistrict_code subdistrict_name  district_code
0              83.0            Pangi             23
1              84.0          Chaurah             23
2              85.0           Saluni             23
3              86.0           Bhalai             23
4              87.0        Dalhousie             23
5              88.0        Bhattiyat             23
6              89.0          Sihunta             23
7              90.0           Chamba             23
8              91.0             Holi             23
9              92.0         Brahmaur             23

In [18]:
df['subdistrict_code'].head(5)

0    83.0
1    84.0
2    85.0
3    86.0
4    87.0
Name: subdistrict_code, dtype: float64

In [16]:
df.columns

Index(['subdistrict_code', 'subdistrict_name', 'district_code'], dtype='object')

In [25]:
df.isna().sum()

subdistrict_code    1
subdistrict_name    1
district_code       0
dtype: int64

In [27]:
df[df.isna().any(axis=1)]

      subdistrict_code subdistrict_name  district_code
1591               NaN              NaN            320

In [28]:
df = df.dropna()

In [29]:
df.isna().sum()

subdistrict_code    0
subdistrict_name    0
district_code       0
dtype: int64

In [33]:
type(df['subdistrict_code'])

pandas.core.series.Series

In [34]:
df['subdistrict_code'] = df['subdistrict_code'].astype(int)

C:\Users\91935\AppData\Local\Temp\ipykernel_3104\3646608509.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['subdistrict_code'] = df['subdistrict_code'].astype(int)

In [35]:
df.head(5)

   subdistrict_code subdistrict_name  district_code
0                83            Pangi             23
1                84          Chaurah             23
2                85           Saluni             23
3                86           Bhalai             23
4                87        Dalhousie             23

In [37]:
df.to_csv("subdistricts1.csv",index=False)

In [38]:
df[df['subdistrict_code'] == 1901]

      subdistrict_code  subdistrict_name  district_code
1361              1901  Tlangnuam (Part)            282
1365              1901  Tlangnuam (Part)            283

In [40]:
df['subdistrict_code'].duplicated().sum()

np.int64(41)

In [43]:
len(df)

5042

In [44]:
df.duplicated().sum()

np.int64(0)

In [58]:
df3 = pd.read_csv(r"C:\Users\91935\DA Projects\capstone_village_api\data_cleaning\clean_data.csv")
df3.head(5)

,state_code,state_name,district_code,district_name,subdistrict_code,subdistrict_name,village_code,village_name,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,2,HIMACHAL PRADESH,23,Chamba,83,Pangi,6673,R.F.Luj (6),NaN,NaN,NaN,NaN,NaN,NaN
1,2,HIMACHAL PRADESH,23,Chamba,83,Pangi,6674,Luj (7),NaN,NaN,NaN,NaN,NaN,NaN
2,2,HIMACHAL PRADESH,23,Chamba,83,Pangi,6675,Dharwas (11),NaN,NaN,NaN,NaN,NaN,NaN
3,2,HIMACHAL PRADESH,23,Chamba,83,Pangi,6676,R.F.Kanyun (8),NaN,NaN,NaN,NaN,NaN,NaN
4,2,HIMACHAL PRADESH,23,Chamba,83,Pangi,6677,R.F.Urnu (9),NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
df3.isna().sum()

state_code               0
state_name               0
district_code            0
district_name            0
subdistrict_code         0
subdistrict_name         0
village_code             0
village_name             0
Unnamed: 0          457053
Unnamed: 1          457053
Unnamed: 2          457053
Unnamed: 3          457053
Unnamed: 4          457053
Unnamed: 5          457053
dtype: int64

In [60]:
df3.isnull().sum()

state_code               0
state_name               0
district_code            0
district_name            0
subdistrict_code         0
subdistrict_name         0
village_code             0
village_name             0
Unnamed: 0          457053
Unnamed: 1          457053
Unnamed: 2          457053
Unnamed: 3          457053
Unnamed: 4          457053
Unnamed: 5          457053
dtype: int64

In [61]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457053 entries, 0 to 457052
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   state_code        457053 non-null  int64
 1   state_name        457053 non-null  object
 2   district_code     457053 non-null  int64
 3   district_name     457053 non-null  object
 4   subdistrict_code  457053 non-null  int64
 5   subdistrict_name  457053 non-null  object
 6   village_code      457053 non-null  int64
 7   village_name      457053 non-null  object
 8   Unnamed: 0        0 non-null       float64
 9   Unnamed: 1        0 non-null       float64
 10  Unnamed: 2        0 non-null       float64
 11  Unnamed: 3        0 non-null       float64
 12  Unnamed: 4        0 non-null       float64
 13  Unnamed: 5        0 non-null       float64
dtypes: float64(6), int64(4), object(4)
memory usage: 48.8+ MB

In [63]:
df3.duplicated().sum()

np.int64(0)

In [68]:
df4 =  pd.read_csv(r"C:\Users\91935\DA Projects\capstone_village_api\data_cleaning\cleaned\villages.csv")
df4.head(15)

    village_code          village_name  subdistrict_code
0           6673          R.F.Luj  (6)                83
1           6674              Luj  (7)                83
2           6675         Dharwas  (11)                83
3           6676       R.F.Kanyun  (8)                83
4           6677         R.F.Urnu  (9)                83
5           6678   D.P.F.Pinchho  (10)                83
6           6679          Kuthah  (12)                83
7           6680         Chaloli  (13)                83
8           6681          Rusmas  (14)                83
9           6682             Tai  (15)                83
10          6683   Sural Bhatori  (16)                83
11          6684    Dhar Shinkal  (17)                83
12          6685  Hundan Bhatori  (18)                83
13          6686          Tundru  (19)                83
14          6687          Takwas  (20)                83

In [69]:
df4.isna().sum()

village_code        0
village_name        0
subdistrict_code    0
dtype: int64

In [70]:
df4[df4.isna().any(axis=1)]

Empty DataFrame
Columns: [village_code, village_name, subdistrict_code]
Index: []

In [73]:
df4.duplicated().sum()

np.int64(0)